# The containers that compose the project
services:
  mysql_db:
    image: mysql:8
    restart: always
    container_name: integration-tests-prisma
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_DATABASE: tests
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  wait-for-db:
    image: atkrad/wait4x
    depends_on:
      mysql_db:
        condition: service_healthy
    command: tcp mysql_db:3306 -t 30s -i 250ms
